#!/usr/bin/env bash
# submit_plot_spearman_g2t_vs_luna.sh
# -----------------------------------------------------------------------------
# Submit a tiny CPU-only LSF job that renders the G2T-vs-LUNA Spearman
# comparison figure. Wraps:
#
#     analysis/benchmarking/plots/plot_spearman_g2t_vs_luna.py
#
# Sized for the normal queue (no GPU, 4 GB, 1 core, 10 min wall) — the
# job is just pandas + matplotlib over ten one-row CSVs, so this is
# wildly over-provisioned but keeps it inside the cluster-friendly
# normal-queue defaults.
#
# Usage:
#     bash submit_plot_spearman_g2t_vs_luna.sh [--dry_run]
#
# The output figure (svg + pdf + png) and the processed CSV land in:
#     /nfs/team361/sb75/scgg-reproducibility/artifacts/
#         mmc_luna/comparison_plots/
#         g2t_vs_luna_spearman.{svg,pdf,png}
#         g2t_vs_luna_spearman_processed.csv
#
# LSF logs land alongside under .../comparison_plots/lsf_logs/<TS>/.
#
# Env knobs (all optional):
#     SCGG_REPO        absolute path to the scgg monorepo (defaults to
#                      /nfs/team361/sb75/scgg). The plotting venv is
#                      reused from there.
#     VENV_PATH        venv to activate. Default:
#                      /nfs/team361/sb75/.venvs/scgg (matches the
#                      scgg pipeline's venv — same pandas + matplotlib).
#     LSF_QUEUE        override the queue. Default: normal.
#     LSF_GROUP        cost-code group. Default: $LSF_GROUP env or s10396.
# -----------------------------------------------------------------------------

set -euo pipefail

DRY_RUN=0
if [[ "${1:-}" == "--dry_run" ]]; then
    DRY_RUN=1
fi

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
REPRO_ROOT="$( cd -- "$SCRIPT_DIR/../../.." &> /dev/null && pwd )"
PLOT_SCRIPT="$REPRO_ROOT/analysis/benchmarking/plots/plot_spearman_g2t_vs_luna.py"

if [[ ! -f "$PLOT_SCRIPT" ]]; then
    echo "ERROR: plot script not found: $PLOT_SCRIPT" >&2
    exit 1
fi

VENV_PATH="${VENV_PATH:-/nfs/team361/sb75/.venvs/scgg}"
LSF_QUEUE_FINAL="${LSF_QUEUE:-normal}"
LSF_GROUP_FINAL="${LSF_GROUP:-s10396}"

ARTIFACTS_ROOT="${SCGG_ARTIFACTS_ROOT:-/nfs/team361/sb75/scgg-reproducibility/artifacts}"
OUT_DIR="$ARTIFACTS_ROOT/mmc_luna/comparison_plots"
RUN_TS="$(date +%Y%m%d_%H%M%S)"
LOG_DIR="$OUT_DIR/lsf_logs/$RUN_TS"
mkdir -p "$LOG_DIR"

JOB_NAME="plot-g2t-vs-luna-$RUN_TS"
LOG_OUT="$LOG_DIR/submit.out"
LOG_ERR="$LOG_DIR/submit.err"

# Self-contained job script — mirrors the submit_pipeline.sh convention
# (kept on disk so the configuration is re-runnable by hand).
JOB_SCRIPT="$LOG_DIR/job.sh"
{
    echo "#!/usr/bin/env bash"
    echo "# Auto-generated by submit_plot_spearman_g2t_vs_luna.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "# Re-runnable: bash $JOB_SCRIPT"
    echo "set -euo pipefail"
    echo
    printf 'source %q\n' "$VENV_PATH/bin/activate"
    printf 'exec python %q\n' "$PLOT_SCRIPT"
} > "$JOB_SCRIPT"
chmod +x "$JOB_SCRIPT"

echo "================================================================"
echo "  submit_plot_spearman_g2t_vs_luna.sh"
echo "================================================================"
echo "plot script   : $PLOT_SCRIPT"
echo "venv          : $VENV_PATH"
echo "queue         : $LSF_QUEUE_FINAL"
echo "group         : $LSF_GROUP_FINAL"
echo "out dir       : $OUT_DIR"
echo "log dir       : $LOG_DIR"
echo "job script    : $JOB_SCRIPT"
echo "dry run       : $DRY_RUN"
echo "================================================================"

BSUB_CMD=(
    bsub
    -G "$LSF_GROUP_FINAL"
    -q "$LSF_QUEUE_FINAL"
    -n 1
    -M 4000
    -R "select[mem>4000] rusage[mem=4000]"
    -W "00:10"
    -J "$JOB_NAME"
    -o "$LOG_OUT"
    -e "$LOG_ERR"
)

if [[ "$DRY_RUN" == "1" ]]; then
    printf '    %q ' "${BSUB_CMD[@]}"
    printf '< %q\n' "$JOB_SCRIPT"
    exit 0
fi

"${BSUB_CMD[@]}" < "$JOB_SCRIPT"
echo "submitted     : $JOB_NAME"
echo "tail logs     :"
echo "    tail -f $LOG_OUT"
echo "    tail -f $LOG_ERR"
