#!/usr/bin/env bash
# submit_compare_per_slice.sh
# -----------------------------------------------------------------------------
# Submit a tiny CPU-only LSF job that compares per-slice metrics
# between one LUNA inference run and one G2T (scGG) inference run, and
# writes a ranking (slices sorted by G2T-vs-LUNA improvement,
# biggest gain on top) to disk. Wraps:
#
#     analysis/benchmarking/plots/compare_per_slice_metrics.py
#
# Tiny job — pandas join over two single-CSV files plus formatted
# print. Sized for the normal queue (no GPU, 4 GB, 1 core, 30 min wall).
#
# Usage:
#     bash submit_compare_per_slice.sh \\
#         --luna_timestamp 20260526_085131 \\
#         --scgg_timestamp 20260530_165229 \\
#         [--metric_col spearman_per_cell_median] \\
#         [--dry_run]
#
# Options:
#   --luna_timestamp TS      YYYYMMDD_HHMMSS of the LUNA inference run.
#                            Required.
#   --scgg_timestamp TS      YYYYMMDD_HHMMSS of the G2T inference run.
#                            Required.
#   --metric_col COL         Column in per_slice_metrics.csv to compute
#                            delta on. Default: spearman_per_cell_median.
#                            Other choices: spearman_per_cell_mean.
#                            (The CSV does NOT contain a "pearson"
#                            column today — pipeline writes Spearman
#                            only.)
#   --dry_run                Print the bsub command without submitting.
#
# Output (lands in
#   /nfs/team361/sb75/scgg-reproducibility/artifacts/mmc_luna/
#       comparison_plots/per_slice_comparisons/):
#
#     per_slice_delta_<metric>_luna_<LUNA_TS>_vs_g2t_<SCGG_TS>.csv
#         Tidy rows: section_label, n_cells, luna, g2t, delta, abs_delta.
#         Sorted biggest-G2T-win first.
#     per_slice_delta_<metric>_luna_<LUNA_TS>_vs_g2t_<SCGG_TS>.txt
#         Same data formatted as a human-readable ranking. The LSF
#         stdout (submit.out) also captures it.
#
# LSF logs land under
#   .../comparison_plots/per_slice_comparisons/lsf_logs/<TS>/.
#
# Env knobs (all optional):
#     VENV_PATH        venv to activate. Default:
#                      /nfs/team361/sb75/.venvs/scgg.
#     LSF_QUEUE        override the queue. Default: normal.
#     LSF_GROUP        cost-code group. Default: team361 (normal queue
#                      rejects sXXXX AI-acceleration groups).
# -----------------------------------------------------------------------------

set -euo pipefail

DRY_RUN=0
LUNA_TS=""
SCGG_TS=""
METRIC_COL=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry_run)
            DRY_RUN=1; shift ;;
        --luna_timestamp)
            LUNA_TS="${2:?--luna_timestamp requires a value}"; shift 2 ;;
        --scgg_timestamp)
            SCGG_TS="${2:?--scgg_timestamp requires a value}"; shift 2 ;;
        --metric_col)
            METRIC_COL="${2:?--metric_col requires a value}"; shift 2 ;;
        --help|-h)
            awk 'NR>1 && /^[^#]/{exit} {print}' "$0"
            exit 0 ;;
        *)
            echo "ERROR: unknown arg: $1" >&2
            echo "Run with --help for usage." >&2
            exit 2 ;;
    esac
done

if [[ -z "$LUNA_TS" ]] || [[ -z "$SCGG_TS" ]]; then
    echo "ERROR: --luna_timestamp and --scgg_timestamp are both required." >&2
    echo "Run with --help for usage." >&2
    exit 2
fi

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
REPRO_ROOT="$( cd -- "$SCRIPT_DIR/../../.." &> /dev/null && pwd )"
PY_SCRIPT="$REPRO_ROOT/analysis/benchmarking/plots/compare_per_slice_metrics.py"

if [[ ! -f "$PY_SCRIPT" ]]; then
    echo "ERROR: python script not found: $PY_SCRIPT" >&2
    exit 1
fi

VENV_PATH="${VENV_PATH:-/nfs/team361/sb75/.venvs/scgg}"
LSF_QUEUE_FINAL="${LSF_QUEUE:-normal}"
# normal queue rejects sXXXX (AI-acceleration) cost-code groups; use
# the project group instead. Set LSF_GROUP=<other> to override.
LSF_GROUP_FINAL="${LSF_GROUP:-team361}"

ARTIFACTS_ROOT="${SCGG_ARTIFACTS_ROOT:-/nfs/team361/sb75/scgg-reproducibility/artifacts}"
OUT_DIR="$ARTIFACTS_ROOT/mmc_luna/comparison_plots/per_slice_comparisons"
RUN_TS="$(date +%Y%m%d_%H%M%S)"
LOG_DIR="$OUT_DIR/lsf_logs/$RUN_TS"
mkdir -p "$LOG_DIR"

JOB_NAME="compare-per-slice-$RUN_TS"
LOG_OUT="$LOG_DIR/submit.out"
LOG_ERR="$LOG_DIR/submit.err"

JOB_SCRIPT="$LOG_DIR/job.sh"
{
    echo "#!/usr/bin/env bash"
    echo "# Auto-generated by submit_compare_per_slice.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "# Re-runnable: bash $JOB_SCRIPT"
    echo "set -euo pipefail"
    echo
    printf 'source %q\n' "$VENV_PATH/bin/activate"
    echo
    # Build the python argv. printf %q safely shell-quotes every value.
    printf 'exec python %q --luna_timestamp %q --scgg_timestamp %q' \
        "$PY_SCRIPT" "$LUNA_TS" "$SCGG_TS"
    if [[ -n "$METRIC_COL" ]]; then
        printf ' --metric_col %q' "$METRIC_COL"
    fi
    printf '\n'
} > "$JOB_SCRIPT"
chmod +x "$JOB_SCRIPT"

echo "================================================================"
echo "  submit_compare_per_slice.sh"
echo "================================================================"
echo "py script       : $PY_SCRIPT"
echo "venv            : $VENV_PATH"
echo "queue           : $LSF_QUEUE_FINAL"
echo "group           : $LSF_GROUP_FINAL"
echo "luna_timestamp  : $LUNA_TS"
echo "scgg_timestamp  : $SCGG_TS"
[[ -n "$METRIC_COL" ]] && echo "metric_col      : $METRIC_COL"
echo "out dir         : $OUT_DIR"
echo "log dir         : $LOG_DIR"
echo "job script      : $JOB_SCRIPT"
echo "dry run         : $DRY_RUN"
echo "================================================================"

BSUB_CMD=(
    bsub
    -G "$LSF_GROUP_FINAL"
    -q "$LSF_QUEUE_FINAL"
    -n 1
    -M 4000
    -R "select[mem>4000] rusage[mem=4000]"
    -W "00:30"
    -J "$JOB_NAME"
    -o "$LOG_OUT"
    -e "$LOG_ERR"
)

if [[ "$DRY_RUN" == "1" ]]; then
    printf '    %q ' "${BSUB_CMD[@]}"
    printf '< %q\n' "$JOB_SCRIPT"
    exit 0
fi

"${BSUB_CMD[@]}" < "$JOB_SCRIPT"
echo "submitted       : $JOB_NAME"
echo "tail logs       :"
echo "    tail -f $LOG_OUT"
echo "    tail -f $LOG_ERR"
